version: '3.3'

services:
  db:
    container_name: um_db
    image: mariadb:10
    restart: always
    volumes:
      - ./db-data:/db-data:rw
  phpmyadmin:
    container_name: um_phpmyadmin
    image: phpmyadmin:5.2-apache
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    depends_on:
      - db
  lumen:
    container_name: um_api
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    build: .
    command: php -S lumen:8000 -t public
    restart: always
    depends_on:
      - db
  swagger:
    container_name: um_swagger
    image: swaggerapi/swagger-ui:v4.15.5
    ports:
      - 82:8080
    environment:
      URL: http://localhost:8000/api-docs
    depends_on:
      - lumen
volumes:
  db-data:
